
export const projectData = [
    {
        imagePath: './images/CbC.png',
        repoName: 'final-project-EM ',
        displayName: 'Carl Berner Cocktailklubb',
        netlifyUrl: 'https://cbc-klubb.netlify.app',
        gitUrl: 'https://github.com/elbines/final-project-EM.git',
        className: 'CBCklubb',
        skills: ["HTML", "CSS", "React", "Express", "Mongo DB", "JWT Tokens", "APIs"],
        text: "Authenticated user register and login, leading to a secured page displayed only to logged in users.",
    },
    {
        imagePath: './images/auth.png',
        repoName: 'em-project-auth',
        displayName: 'Authenciation App',
        netlifyUrl: 'https://em-authorization.netlify.app/',
        gitUrl: 'https://github.com/mirelcac/em-project-auth.git',
        className: 'Authentication',
        skills: ["HTML", "CSS", "React", "React-Router", "Express", "Mongo DB", "JWT Tokens", "APIs"],
        text: "Welcome, about, and explore pages. Admin panel secured through token & role authentication, allowing admin reigistration, user lists and upload/ edit/ delete recipes/ pictures.",
    },
    {
        imagePath: './images/yoga.png',
        repoName: 'project-yoga-vite',
        displayName: 'YogaBalance',
        netlifyUrl: 'https://yoga-balance.netlify.app',
        gitUrl: 'https://github.com/elbines/project-yoga-vite.git',
        className: 'YogaBalance',
        skills: ["HTML", "CSS", "React", "React-Router", "i18next"],
        text: "Responsive React application built from a Figma design handoff. Focus on layout accuracy, responsive behavior across devices, and internationalization.",
    },
    {
        imagePath: './images/HPquizz.png',
        repoName: '',
        displayName: 'The Quizzard Tournament',
        netlifyUrl: 'https://theharrypotterquiz.netlify.app/',
        gitUrl: '',
        className: 'HpQuiz',
        skills: ["HTML", "CSS", "React", "React-Router", "Zustand"],
        text: "A Quizzard Tournament where you can test you Harry Potter knowledge and skills! With focus on React, Routes, and Styling.",
    },
    {
        imagePath: './images/QR-code.png',
        repoName: 'project-QR-code-generator-vite',
        displayName: 'QR-Code Generator',
        netlifyUrl: 'https://qr-code-generator-ec.netlify.app',
        gitUrl: 'https://github.com/elbines/project-QR-code-generator-vite.git',
        className: 'QRcodeGenerator',
        skills: ["HTML", "CSS", "React", "React-Router", "APIs"],
        text: "Generate and download QR codes from URLs, utilising custom hooks for efficient state management..",
    },

    {
        imagePath: './images/HappyTh.png',
        repoName: 'project-happy-thoughts-elbine-vite',
        displayName: 'Happy Thoughts',
        netlifyUrl: 'https://happy-thoughts-elbine.netlify.app',
        gitUrl: 'https://github.com/elbines/project-happy-thoughts-elbine-vite',
        className: 'HappyThoughts',
        skills: ["HTML", "CSS", "React", "APIs"],
        text: "This is a social networking platform reminiscent of Twitter, where you can share your positive thoughts and express appreciation for others' posts by clicking the 'like' button.",
    },
    {
        imagePath: './images/movie.png',
        repoName: 'project-movies-vite',
        displayName: 'Movie Browser',
        netlifyUrl: 'https://wk9-project-movie-site-c05bc5.netlify.app/',
        gitUrl: 'https://github.com/elbines/project-music-releases-elbine',
        className: 'MusicMoviesRelease',
        skills: ["HTML", "CSS", "React", "React-Router", "APIs"],
        text: "Showcase movies and movie details through utilizing themoviedb.org's API. Fetch API, rendering movie specifics, and managing routes.",
    },
    /*
        {
            imagePath: './images/weatherapp.png',
            repoName: 'EmE-weather-app',
            displayName: 'Weather App',
            netlifyUrl: 'https://eme-weather-app.netlify.app/',
            gitUrl: 'https://github.com/elbines/EmE-weather-app',
            className: 'WeatherApp',
            skills: ["HTML", "CSS", "JavaScript"],
            text: "My teams version of a Weather App is crafted using Vanilla JavaScript and fetches its data from an API. I'm looking forward to enhancing its functionalities and design in the future."
        },
    
    {
        imagePath: './images/GuessSong.jpg',
        repoName: 'project-guess-who-elbine',
        displayName: 'Game: Guess the song',
        netlifyUrl: 'https://guess-who-elbine.netlify.app/',
        gitUrl: 'https://github.com/elbines/project-guess-who-elbine',
        className: 'GuessSong',
        skills: ["HTML", "CSS", "JavaScript"],
        text: "This game, originally designed as a 'guess who' challenge, has been transformed into a 'guess the song' experience. With each new game, a different secret song is automatically selected.",
    },
        {
        imagePath: './images/MusicRelease.png',
        repoName: 'project-music-releases-elbine',
        displayName: 'New music releases',
        netlifyUrl: 'https://app.netlify.com/sites/music-releases-by-elbine/overview',
        gitUrl: 'https://github.com/elbines/project-music-releases-elbine',
        className: 'MusicRelease',
        skills: ["HTML", "CSS", "React"],
        text: "This React-based app displays the 50 latest music albums sourced from Spotify, allowing you to explore these albums and access the respective artist's Spotify profile.",
    },*/

    {
        imagePath: './images/Pala.png',
        repoName: 'project-survey-vite-EMS',
        displayName: 'Pala Survey',
        netlifyUrl: 'https://pala-customer-survey.netlify.app',
        gitUrl: 'https://github.com/elbines/project-survey-vite-EMS',
        className: 'PalaSurvey',
        skills: ["HTML", "CSS", "React"],
        text: "We collaborated as a team to create this initial survey draft for Pala, keeping real-world business scenarios in mind. We hope the form can evolve and be useful for the company.",
    },


];
